<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Application backend based on ZF2'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() . '/css/style.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body>
<div class="container">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('login/process', array('action' => 'authenticate')));
    $form->prepare();
    ?>
    <div class="login-container">
        <h1><?php echo $this->translate('Login'); ?></h1>
        <div class="login-form">
            <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formCollection($form); ?>
            <?php echo $this->form()->closeTag(); ?>

            <?php if ($this->messages): ?>
            <ul class="form-messages">
            <?php foreach($this->messages as $message): ?>
                <li><?php echo $this->translate($message); ?></li>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </div>
    </div>
    <hr>
    <footer>
        <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
