<?php if ($this->pages): ?>
<div class="breadcrumbs" itemprop="breadcrumb">
    <?php foreach ($this->pages as $page): ?>
        <?php /** @var \Zend\Navigation\Page\Mvc $page */?>
        <?php if ($page->isActive()) { break; } ?>
        <a href="<?php echo $page->getHref(); ?>" title="<?php echo $this->translate($page->getLabel()); ?>"><?php echo $this->translate($page->getLabel()); ?></a>&nbsp;&nbsp;/&nbsp;&nbsp;
    <?php endforeach; ?>
</div>
<?php endif; ?>
