<div>
    <a data-toggle="modal" data-target="#myModal" href="<?php echo $this->url('root/lesson-request'); ?>" title="<?php echo $this->translate('Trial lesson'); ?>"><?php echo $this->translate('Trial lesson'); ?></a>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>
