<div class="one-column" itemscope itemtype="http://schema.org/EducationalOrganization">
    <div class="contacts">
        <h1><?php echo $this->translate('Contacts'); ?></h1>
        <div class="left phone">
            <h2><i><?php echo $this->translate('Phones'); ?></i></h2>
            <table>
                <tr>
                    <td><span itemprop="telephone">(063) 764-5447</span></td>
                </tr>
            </table>
        </div>
        <div class="left email">
            <h2><i><?php echo $this->translate('Email'); ?></i></h2>
            <a itemprop="email" href="mailto:safetycarukraine@gmail.com" title="safetycarukraine@gmail.com" target="_top">safetycarukraine@gmail.com</a>
        </div>
        <div class="left schedule">
            <h2><i><?php echo $this->translate('Working hours'); ?></i></h2>
            <p>Понедельник &mdash; пятница с 8:00 до 20:00</p>
            <p>Суббота, воскресенье &mdash; выходные дни</p>
        </div>
        <div class="clear-both"></div>
        <div class="address" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
            <h2><i><?php echo $this->translate('Address'); ?></i></h2>
            <p><strong><span itemprop="addressLocality">Киев</span>, <span itemprop="streetAddress">ул. Метрологическая</span></strong></p>
            <div class="map-container">
                <iframe src="https://www.google.com/maps/embed?pb=!1m22!1m12!1m3!1d2545.788963154966!2d30.472520874313357!3d50.3518414435941!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m7!1i0!3e0!4m0!4m3!3m2!1d50.3529585!2d30.4716229!5e0!3m2!1sru!2s!4v1404338930681" width="100%" height="390" frameborder="0" style="border:0"></iframe>
            </div>
        </div>
    </div>
</div>
