<?php
if ($GLOBALS['wp_query']->max_num_pages < 2) {
    return;
}
$paged        = get_query_var('paged') ? intval(get_query_var('paged')) : 1;
$pagenum_link = html_entity_decode(get_pagenum_link());
$query_args   = array();
$url_parts    = explode('?', $pagenum_link);
if (isset($url_parts[1])) {
    wp_parse_str($url_parts[1], $query_args);
}
$pagenum_link = remove_query_arg(array_keys($query_args), $pagenum_link);
$pagenum_link = trailingslashit($pagenum_link) . '%_%';
$format  = $GLOBALS['wp_rewrite']->using_index_permalinks() && ! strpos($pagenum_link, 'index.php') ? 'index.php/' : '';
$format .= $GLOBALS['wp_rewrite']->using_permalinks() ? user_trailingslashit('page/%#%', 'paged') : '?paged=%#%';

$links = paginate_links(array(
    'base'          => @add_query_arg('paged', '%#%'),
    'format'        => '?paged=%#%',
    'current'       => $paged,
    'total'         => $GLOBALS['wp_query']->max_num_pages,
    'prev_next'     => true,
    'prev_text'     => 'Previous',
    'next_text'     => 'Next',
));
if ($links): ?>
    <section class="pagination">
        <p><?php echo $links; ?></p>
    </section>
<?php endif; ?>
